wallpaper setup ready

diff --git a/available/x11-dwm/dot-local/bin/wallpaper b/available/x11-dwm/dot-local/bin/wallpaper
--- a/available/x11-dwm/dot-local/bin/wallpaper
+++ b/available/x11-dwm/dot-local/bin/wallpaper
@@ -1,7 +1,7 @@
 #!/bin/bash
 
-FOLDER="~/Downloads/Images"
-SCRIPT
+FOLDER=~/Pictures
+SCRIPT="$HOME/.local/bin/dwm_rebuild"
 
 menu() {
   if command -v nsxiv >/dev/null; then
@@ -11,10 +11,18 @@ menu() {
   fi
 
   case $CHOICE in
-  Random) wal -i "$FOLDER" -o $SCRIPT ;; # dmenu random option
-  *.*) wal -i "$CHOICE" -o $SCRIPT ;;
+  Random) wal -i "$FOLDER" -o "$SCRIPT" ;; # dmenu random option
+  *.*) wal -i "$CHOICE" -o "$SCRIPT" ;;
   *) exit 0 ;;
   esac
+}
+
+set_wallpaper() {
+  wal -i "$1" -o "wallpaper refresh"
+}
+
+refresh() {
+  dwm_rebuild
 }
 
 # If given arguments:
@@ -23,7 +31,11 @@ menu() {
 
 case "$#" in
 0) menu ;;
-1) wal -i "$1" -o $SCRIPT ;;
-2) wal -i "$1" --theme $2 -o $SCRIPT ;;
-*) exit 0 ;;
+*) echo ">$@<" ;;
+esac
+
+case $1 in
+menu) menu ;;
+refresh) refresh ;;
+*) echo "Invalid arguments :( $1 $@" && exit 1 ;;
 esac
